# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {2147483645}  -id {IP_Flow 19-3152}  -string {{WARNING: [IP_Flow 19-3152] Bus Interface 'PBLRC': ASSOCIATED_BUSIF bus '' does not exist.}}  -suppress 
set_msg_config  -ruleid {2147483646}  -id {IP_Flow 19-3152}  -string {{WARNING: [IP_Flow 19-3152] Bus Interface 'BCLK': ASSOCIATED_BUSIF bus '' does not exist.}}  -suppress 
set_msg_config  -ruleid {2147483647}  -id {Vivado 12-3481}  -string {{ERROR: [Vivado 12-3481] Cannot replace a file with itself: '/home/jaxc/FPGA/IP/I2s_IP/I2s_IP.srcs/sources_1/ip/blk_mem_gen_0/BLK_init.coe'}}  -suppress 
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.cache/wt [current_project]
set_property parent.project_path /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /home/jaxc/FPGA/IP [current_project]
set_property ip_cache_permissions disable [current_project]
read_ip -quiet /home/jaxc/FPGA/IP/clk_wiz_0/clk_wiz_0.xci
set_property is_locked true [get_files /home/jaxc/FPGA/IP/clk_wiz_0/clk_wiz_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top clk_wiz_0 -part xc7z010clg400-1 -mode out_of_context

rename_ref -prefix_all clk_wiz_0_

write_checkpoint -force -noxdef clk_wiz_0.dcp

catch { report_utilization -file clk_wiz_0_utilization_synth.rpt -pb clk_wiz_0_utilization_synth.pb }

if { [catch {
  write_verilog -force -mode synth_stub /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

add_files /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_stub.v -of_objects [get_files /home/jaxc/FPGA/IP/clk_wiz_0/clk_wiz_0.xci]

add_files /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_stub.vhdl -of_objects [get_files /home/jaxc/FPGA/IP/clk_wiz_0/clk_wiz_0.xci]

add_files /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_sim_netlist.v -of_objects [get_files /home/jaxc/FPGA/IP/clk_wiz_0/clk_wiz_0.xci]

add_files /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_sim_netlist.vhdl -of_objects [get_files /home/jaxc/FPGA/IP/clk_wiz_0/clk_wiz_0.xci]

add_files /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp -of_objects [get_files /home/jaxc/FPGA/IP/clk_wiz_0/clk_wiz_0.xci]

if {[file isdir /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.ip_user_files/ip/clk_wiz_0]} {
  catch { 
    file copy -force /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_sim_netlist.v /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.ip_user_files/ip/clk_wiz_0
  }
}

if {[file isdir /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.ip_user_files/ip/clk_wiz_0]} {
  catch { 
    file copy -force /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_sim_netlist.vhdl /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.ip_user_files/ip/clk_wiz_0
  }
}

if {[file isdir /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.ip_user_files/ip/clk_wiz_0]} {
  catch { 
    file copy -force /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_stub.v /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.ip_user_files/ip/clk_wiz_0
  }
}

if {[file isdir /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.ip_user_files/ip/clk_wiz_0]} {
  catch { 
    file copy -force /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.runs/clk_wiz_0_synth_1/clk_wiz_0_stub.vhdl /home/jaxc/FPGA/IP/I2s_IP/I2s_IP.ip_user_files/ip/clk_wiz_0
  }
}
