# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/i2s.xdc

# IP: ip/Output_buffer_Block_RAM/Output_buffer_Block_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Output_buffer_Block_RAM || ORIG_REF_NAME==Output_buffer_Block_RAM}]

# XDC: ip/Output_buffer_Block_RAM/Output_buffer_Block_RAM_ooc.xdc
